#Defino imagen
FROM python:3.10-slim-buster

#Copiar directorio con toda la app al container
WORKDIR /app
COPY . /app

#Cargo los módulos de python que require la app
COPY requirements.txt requirements.txt
RUN pip install -r reqs.txt

CMD app.py
