#Defino imagen
FROM python:3.10-slim-buster

#Copiar directorio con toda la app al container
COPY /Version-05_docker /app
WORKDIR /app

#Cargo los módulos de python que require la app
COPY requerimientos.txt reqs.txt
RUN pip install -r reqs.txt

CMD app.py
